### ISSUE TITLE
Resolved "The requested operation could not be completed due to an error communicating with the server."

### ISSUE THREAD

**Issue by KNNMMDV** [DaRkD0G/Easy-Game-Center-Swift#1]
"The requested operation could not be completed due to an error communicating with the server."
Why is that happening?

**Comment by DaRkD0G** [comment]
Have you add the GameKit, SystemConfiguration frameworks to your Xcode project ?

**Comment by KNNMMDV** [comment]
Yes I have. And it says "[AuthenticationActions] Player not authentified" but I typed my leaderboard id into "leaderboardIdentifier != "xxxOnline.Leaderboard" {". Is there anything else I have to do?

**Comment by DaRkD0G** [comment]
When you launch your project you authentified on the Game Center ? or not ?

Because i your are not authentified you can't open the Game Center.

**Comment by KNNMMDV** [comment]
I logged in my Game Center account. I enabled Game Center from iTunes Connect and created a leaderboard. It is still saying "[AuthenticationActions] Player not authentified"

**Comment by DaRkD0G** [comment]
Hum, Could you try to add this in your UIViewcontroller ? And tell me what shows the terminal ?

    override func viewDidLoad() {
        super.viewDidLoad()

        EasyGameCenter.sharedInstance(self)
        EasyGameCenter.debugMode = true
    }
    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        EasyGameCenter.delegate = self
    }

**Comment by KNNMMDV** [comment]
Do you know why is this keeping repeating? 
[AuthenticationActions] Player Authentified


[Easy Game Center] Couldn't load achievementInformation, error: Error Domain=GKErrorDomain Code=3 "The requested operation could not be completed due to an error communicating with the server." UserInfo=0x7ffa7bca91d0 {GKServerStatusCode=5044, NSLocalizedDescription=The requested operation could not be completed due to an error communicating with the server., NSUnderlyingError=0x7ffa7bc8abe0 "The operation couldn’t be completed. status = 5044, SözTap does not support achievements"}

**Comment by DaRkD0G** [comment]
See that 
http://stackoverflow.com/questions/25891250/game-center-authentication-doesnt-work-in-ios-8

Is coming of apple server and not Easy Game Center

**Comment by DaRkD0G** [comment]
--> Try to active SandBox and your simulator i think is that.

See this post : http://stackoverflow.com/questions/25891250/game-center-authentication-doesnt-work-in-ios-8
