### ISSUE TITLE
Endless loop  "CantCachingA"

### ISSUE THREAD

**Issue by imJustik** [DaRkD0G/Easy-Game-Center-Swift#12]
Hi, sorry for my English. I have a problem. A lot of message in my log. How i can fix it? 
![2015-10-09 11 48 02](https://cloud.githubusercontent.com/assets/8009516/10389645/e352e0f4-6e7b-11e5-8959-8a75221798af.png)
![2015-10-09 11 48 03](https://cloud.githubusercontent.com/assets/8009516/10389652/f21f325e-6e7b-11e5-9f79-0fa59b4a45b2.png)
![2015-10-07 16 26 09](https://cloud.githubusercontent.com/assets/8009516/10389665/09a0f1ce-6e7c-11e5-8216-a23def92b7db.png)

**Comment by DaRkD0G** [comment]
Hi,

Delete EasyGameCenter.delegate = self

Have you create some achievements ? On ituneconnect ?


Cordialement,
Stephan Yannick

Stephan Yannick / Ingénieur Développeur Mobile stephan.yannick@me.com / +33 7 60 55 29 29
YannickStephan.com

**Comment by imJustik** [comment]
Thank you very much. I delete " EasyGameCenter.delegate = self " and add achievements on ituneconnect, it's work! But what did message mean?  "no bundle for bundleID: (null)" 
I have this app in my ituneconnect 
![2015-10-09 14 17 23](https://cloud.githubusercontent.com/assets/8009516/10392528/85d4b97e-6e90-11e5-924d-1efaec4bb751.png)
![2015-10-09 14 19 43](https://cloud.githubusercontent.com/assets/8009516/10392566/db6f833c-6e90-11e5-87d8-e4855ff02a7c.png)

**Comment by DaRkD0G** [comment]
Ok do you use CacoaPods ? or have just import my project ?

For "no bundle for bundleID: (null)"  Try doing a clean of your project.

**Comment by imJustik** [comment]
Just import EasyGameCenter.swift in my SpriteKit project

**Comment by DaRkD0G** [comment]
It's a bug, clear your project reboot your Mac.
