### ISSUE TITLE
Does this support turn based gaming?

### ISSUE THREAD

**Issue by ExplicitG** [DaRkD0G/Easy-Game-Center-Swift#13]
Hi,

I'm attempting to make a turn based game but I'm unsure how to progress next. Does Easy Game Center even support turn based gaming? I can get into a match using:

EasyGameCenter.findMatchWithMinPlayers(2, maxPlayers: 2) 

Once in a match I transition to the game viewcontroller:

 func easyGameCenterMatchStarted() {
        print("\n[MultiPlayerActions] Match Started !")
//        When matchmaking is complete present Story View Controller.
        let vc = self.storyboard?.instantiateViewControllerWithIdentifier("storyID") as! StoryViewController
        self.presentViewController(vc, animated: true, completion: nil)
    }

Now I'm lost on how to implement a turn system and send text inputs to each player.

I'm trying to follow this tutorial http://www.raywenderlich.com/5480/beginning-turn-based-gaming-with-ios-5-part-1

Any ideas?

Thank you.

**Comment by DaRkD0G** [comment]
Easy Game Center supports games per round or live.

It is Easy ;)

1. Look my example project.

2. In your UIViewController add delegate "EasyGameCenterDelegate"

3. add this methods
```swift 
    /**
        Match Start, Delegate Func of Easy Game Center
    */
    func easyGameCenterMatchStarted() {
       /// This method is call when the match started 
        println("\n[MultiPlayerActions] Match Started !")
    }
    /**
        Match Recept Data, Delegate Func of Easy Game Center
    */
    func easyGameCenterMatchRecept(match: GKMatch, didReceiveData data: NSData, fromPlayer playerID: String) {
       /// This methods recept data by other player and the actually player
        println("\n[MultiPlayerActions] Recept Data from Match !")
    }
    /**
    Match End / Error (No NetWork example), Delegate Func of Easy Game Center
    */
    func easyGameCenterMatchEnded() {
       /// When the game finished
        println("\n[MultiPlayerActions] Match Ended !")
    }
    /**
    Match Cancel, Delegate Func of Easy Game Center
    */
    func easyGameCenterMatchCancel() {
       /// if player cancel the game
        println("\n[MultiPlayerActions] Match cancel")
    }
```

**Comment by ExplicitG** [comment]
Ah ok, thanks. Just trying to figure out how to create turns and send user inputted text each turn for this http://www.raywenderlich.com/5480/beginning-turn-based-gaming-with-ios-5-part-1. So just wanted to know I wasn't wasting my time using EGC :)
