### ISSUE TITLE
No achievement cached

### ISSUE THREAD

**Issue by Dean151** [DaRkD0G/Easy-Game-Center-Swift#15]
Hi !

I use Easy Game Center Swift in my app, but somehow I could make Achievements to work.
I created it in iTunes connect, like my leaderboards.
The leaderboards works fines, but the achievements are unfindable : 
`[Easy Game Center] No Achievement for identifier`

The achievements are marked as "Not available" in iTunes Connect, just like the Leaderboards, because i've not released anything yet.

Anyway, when I look for cached achievements in EGC, I find an empty dictionary. Are the achievements are fetched correctly ? Why I am missing for achievements ?

**Comment by DaRkD0G** [comment]
If I understood correctly you havent't achievement in your game but you have leaderboards ?

If it's that, I had not planned that the coder is only the classification ... But he have leaderboards and Achievements...

Do you create some achievement ? or just leaderboard, because if is that, i am going working for update my project for you can juste have leaderboard or achievement or both

**Comment by DaRkD0G** [comment]
Mais attend Dean151 tes français ?

**Comment by DaRkD0G** [comment]
Donc si j'ai bien compris tu as créer que un leaderboard ? et aucun achievement c'est ca ?

**Comment by Dean151** [comment]
J'ai créé les deux, cependant je ne trouve aucune réalisation dans le cache de EGC. 
Je n'ai sans doute pas bien compris comment fonctionnait les réalisations dans ta lib.
J'ai réglé le problème en changeant de lib. 
Je suis arrivé à la conclusion que ta lib était trop compliquée pour mes besoins. 
J'utilise GCHelper maintenant

**Comment by DaRkD0G** [comment]
Tu ne trouve aucune réalisation c'est bizarre car elles sont misent dans le cache.

Tu peux prendre un screen shoot du debug ou le début en lui même ?

Pourtant ma librairie et la plus simple possible d'utilisation 

Cordialement,
Stephan Yannick

Stephan Yannick / Ingénieur Développeur Mobile stephan.yannick@me.com / +33 7 60 55 29 29
YannickStephan.com

**Comment by DaRkD0G** [comment]
Tu as fait un test avec l'exemple proposer ?

Cordialement,
Stephan Yannick

Stephan Yannick / Ingénieur Développeur Mobile stephan.yannick@me.com / +33 7 60 55 29 29
YannickStephan.com

**Comment by DaRkD0G** [comment]
Et bien après des tests et avoir contacter les personnes utilisant cette version il n'y aucun problème.

Celui viens soit de ton projet ou autre.


Voila.

**Comment by DaRkD0G** [comment]
Close
