### ISSUE TITLE
[Resolved] fatal error: can't unsafeBitCast between types of different sizes

### ISSUE THREAD

**Issue by woolardjason** [DaRkD0G/Easy-Game-Center-Swift#19]
Getting this error "fatal error: can't unsafeBitCast between types of different sizes" when trying to use the Multiplayer feature. It's in the function lookupPlayers() in EasyGameCenter.swift. Using latest iOS and Xcode releases.

let playerIDs = match.players.map { $0 .playerID } as! [String]

**Comment by DaRkD0G** [comment]
Ok I'll look to my side

**Comment by DaRkD0G** [comment]
Please try the new version 2.2.0

Update your file with CocoaPods.

Called me if you still have the error

**Comment by woolardjason** [comment]
That seemed to fix that error, thank you for your help. Did you happen to get Multiplayer to work with iOS9? I keep getting this in console: plugin com.apple.GameCenterUI.GameCenterMatchmakerExtension invalidated

**Comment by DaRkD0G** [comment]
Cool :)

well my side on ios 9 this works. All return to tell me that works

When is show that message ?

Cordialement,
Stephan Yannick

Stephan Yannick / Ingénieur Développeur Mobile stephan.yannick@me.com / +33 7 60 55 29 29
YannickStephan.com
