### ISSUE TITLE
[Question] tvOS : User has canceled authentication

### ISSUE THREAD

**Issue by rmvz3** [DaRkD0G/Easy-Game-Center-Swift#22]
Is this library tvOS friendly?

I can't even log in because I always get the above error. No effect starting logged or not.

Thx

**Comment by DaRkD0G** [comment]
Yes you can use EGC for tvOS :) 

Can you explain a little more the problem?

**Comment by rmvz3** [comment]
Well, I'm glad to read that. :)

Well, in fact I can't say any more than that. I've made my tvOS Swift GameViewController EGCDelegate, I have EGC.sharedInstance(self) and EGC.debugmode = true in viewDidLoad() and EGC.delegate = self in viewDidAppear. I have GameKit and SystemConfiguration frameworks too, but when I start the game (ATV or simmulator) I just get the "User has canceled authentication" message and EGCAuthentified is not even called.

I thought there would be any kind of incompatibility of your library with tvOS but if that's not the case, could be anything related to my own gamecenter account? (I'm pretty sure everything is ok on iTC side).

Thanks

**Comment by rmvz3** [comment]
Don't ask me why but suddenly today I launched a game on my Apple TV and the GC welcome banner appeared so I tried my own game (with your library and… just worked (?)

I think something funny happened to my account (messages stopped working a month ago and never came back again)

Thank you for your help. I'm closing this issue.
