### ISSUE TITLE
[Question]: How would I find local players only?

### ISSUE THREAD

**Issue by rjgdesign** [DaRkD0G/Easy-Game-Center-Swift#24]
Hey!

Awesome library, a++.

Just wanting to know, how can I find player on a local network only?

Thanks!

**Comment by DaRkD0G** [comment]
Hi

With that 

Multi :+1: 
    if let players = EGC.getPlayerInMatch() {
        for player in players{
            print(player.alias)
        }
    }

**Comment by DaRkD0G** [comment]
Local

EGC.getLocalPlayer

**Comment by DaRkD0G** [comment]
It resolved ?

**Comment by rjgdesign** [comment]
Ah sorry - I meant when it's finding players, searching for players, I only want it to search for players on the same network, nearby players.
