### ISSUE TITLE
Xcode 7.1.1 Update...

### ISSUE THREAD

**Issue by enterpriser1701** [DaRkD0G/Easy-Game-Center-Swift#25]
Can you update this project for Xcode 7.1.1.?  I get errors when I convert it to 7.1.1.  and I cannot figure out how to fix it.
Thank you.

**Comment by DaRkD0G** [comment]
Yes i see that. 
I make a update to night

**Comment by DaRkD0G** [comment]
If update

**Comment by DaRkD0G** [comment]
is update.
