### ISSUE TITLE
Hidden automatique login of game center

### ISSUE THREAD

**Issue by andrewfashion** [DaRkD0G/Easy-Game-Center-Swift#4]
Is there a way to have it not auto pull up game center login, and make it show only when you hit login?

No matter what I do, it shows the game center login as soon as the app launches.

**Comment by DaRkD0G** [comment]
Hi, You want turn off the open page for the game center login ? that's right ?

**Comment by DaRkD0G** [comment]
Update 3.5 i have add this 

Hidden automatique page for login to Game Center if player not login
EasyGameCenter.showLoginPage = false

Add this code in viewDidLoad after instance of Easy Game Center

**Comment by DaRkD0G** [comment]
Question is finish
