### ISSUE TITLE
[Easy Game Center Swift 2.0] Bad Access - class func localPlayer() -> GKLocalPlayer! {return localPlayer()}

### ISSUE THREAD

**Issue by hsmitty93** [DaRkD0G/Easy-Game-Center-Swift#5]
I'm using xcode 7 beta 3, in swift 2.0. When the game starts up, it crashes and shows the message: "warning: could not load any Objective-C class information from the dyld shared cache. This will significantly reduce the quality of type information available." and places the point of the crash at: class func localPlayer() -> GKLocalPlayer! {return localPlayer()} under Public Func Other in the EasyGameCenter.swift file

**Comment by hsmitty93** [comment]
I figured it out, with help from a StackOverflow question. But I do have another issue, that when I try to report score, it says in the console log as no bundle for bundleID: (null)

**Comment by DaRkD0G** [comment]
Hi could you use this easy game center 
http://bit.ly/1MMDe5Q

Is for swift 2.0

**Comment by hsmitty93** [comment]
Sorry, I am, but I must have clicked on the wrong page to put the issue under.

**Comment by DaRkD0G** [comment]
Ok have you add the framework GameKit and systemConfiguration ?

**Comment by DaRkD0G** [comment]
Your achievements and scores are create ?

**Comment by DaRkD0G** [comment]
If you use  xcode 7 beta 3 and see message error is because Xcode is beta and have lot of problem.
But my project work

**Comment by DaRkD0G** [comment]
Now Work Go to https://github.com/DaRkD0G/Easy-Game-Center-Swift
