### ISSUE TITLE
Question : Build Errors on XCode 7.0 beta 5 

### ISSUE THREAD

**Issue by wheeliebin** [DaRkD0G/Easy-Game-Center-Swift#6]
I'm seeing quite a few build errors in EasyGameCente.swift which appear to be caused by changes in Swift 2 (such as: '#' has been removed from Swift;)

**Comment by DaRkD0G** [comment]
Yes I know, I will transfer the project this afternoon. Currently I have a problem with the transferred with git ...

**Comment by DaRkD0G** [comment]
Please go here  for the swift 2.0 https://github.com/DaRkD0G/Easy-Game-Center-Swift-2.0

 I will transfer the project this afternoon for the Swift 2.0

**Comment by DaRkD0G** [comment]
I have update for Xcode Beta 7 go here https://github.com/DaRkD0G/Easy-Game-Center-Swift-2.0
