### ISSUE TITLE
CantCachingA repeating in log?

### ISSUE THREAD

**Issue by ExplicitG** [DaRkD0G/Easy-Game-Center-Swift#7]
Hi,

Every time I run my app the following  in my Debug log keeps on repeating:

CantCachingA
Sep 19 17:46:37  App Name[2244] <Warning>: 17:46:37.929378 [NSLog]: no bundle for bundleID: (null)

Is it possible to stop this from happening? Its making it really difficult to find errors in the log. Thanks!

**Comment by DaRkD0G** [comment]
Could you tell me what is your version of EasyGameCenter ?

**Comment by DaRkD0G** [comment]
Hi ok i find where is the problem, i fixe this in 2 minutes

**Comment by DaRkD0G** [comment]
I solved the problem, please download the new version EGC 1.01. Thanks for the report

**Comment by DaRkD0G** [comment]
Solve
